### ISSUE TITLE
need documentation on how to use this extension in VSCode

### ISSUE THREAD

**Issue by javaswinger** [cqframework/vscode-cql#26]
I created a self contained CQL measure and after right clicking on the file in VisualStudioCode and selecting "View ELM" I see the full ELM file without any CQL-to-ELM issues.

When I then right click and select "Execute CQL" it shows me the folders that I have to create on my Microsoft Windows laptop to place my content. I am getting an error as well:

Caused by: java.lang.IllegalArgumentException: Could not load source for library MyMeasure, version null.
	at org.cqframework.cql.cql2elm.PriorityLibrarySourceLoader.getLibrarySource(PriorityLibrarySourceLoader.java:72)
	at org.cqframework.cql.cql2elm.LibraryManager.translateLibrary(LibraryManager.java:208)
	at org.cqframework.cql.cql2elm.LibraryManager.resolveLibrary(LibraryManager.java:184)
	at org.opencds.cqf.cql.evaluator.engine.execution.TranslatingLibraryLoader.translate(TranslatingLibraryLoader.java:125)

1. I am unclear on what belongs in this folder:
No data found at c:\Users\revans\Documents\MyMeasures\input\tests. Evaluation may fail if data is required.
I placed dataFHIR Bundle with patient data and a single FHIR Measure in this folder, but maybe it is looking for a specific file name?
What belongs in this folder?

2. this one is obvious as I placed both of my two ValueSets in this folder:
Terminology path: c:\Users\revans\Documents\MyMeasures\input\vocabulary\valueset

3. since this is a measure my CQL has a parameter so I was expecting a right menu entry like "Execute CQL with parameters"
I am unclear how to specify a measure period like I do when I run CQL-ruler using PostMan from a local instance of https://github.com/DBCG/cqf-ruler

5. when I split up my single CQL into separate libraries it executes but I would like to know how to debug the CQL as I used to be able to do in the Atom plugin

**Comment by JPercival** [comment]
Check out the user guide here:
https://github.com/cqframework/vscode-cql/wiki/User-Guide
