### ISSUE TITLE
execute CQL

### ISSUE THREAD

**Issue by jcdufour** [cqframework/vscode-cql#8]
Hello,
With the CQL extension added to VSCode, syntax highlighting works fine, but how do I execute CQL? The context menu "Execute CQL" does not work. Is there anything to set up ?
Thanks for your help

**Comment by dcw312** [comment]
I don’t know, but I suspect it follows the same code-by-convention as the atom plug in. This requires a specific directory input structure for test data. 
https://atom.io/packages/language-cql-preview

**Comment by dcw312** [comment]
I think it’s this structure. @JPercival can you confirm or supply better link?

https://github.com/cqframework/ecqm-content-r4

**Comment by JPercival** [comment]
This is currently the best reference for the directory structure:
https://github.com/cqframework/sample-content-ig

The README has some additional details.

If the "evaluate CQL" context menu doesn't show up after that please let me know

**Comment by brynrhodes** [comment]
Closing as resolved, @jcdufour feel free to submit a new issue or reopen if the issue persists.
