### ISSUE TITLE
Intellisense does not display return type

### ISSUE THREAD

**Issue by drthyl** [cqframework/vscode-cql#9]
Hello,

Is it possible to have the intellisense display the return types of CQL statements (like the example below)? This does not appear to be working in the current extension.
![Screenshot 2022-05-04 210016](https://user-images.githubusercontent.com/82893468/166850127-3305dece-586c-4608-8a58-50009b17cd95.png)

Thank you,
Dorothy

**Comment by dcw312** [comment]
I expect this is a good feature request but would require significant development. @JPercival @brynrhodes i suggest closing this as a suggestion.

**Comment by drthyl** [comment]
Yes, this would be a great feature for Measure Developers developing measures in CQL. I would appreciate your consideration. Thank you!

**Comment by brynrhodes** [comment]
Addressed in 0.2.0 release
